# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 444320d27df2e4a84801a0a5bff374f040c63f2e920fb349fccbd8e14329b17f47c73cd03021363b024ad53f3c9b1a3e58631cd1ff161ff017df8714b75d6d62

test:
  secret_key_base: eb74bae81c683e9537d193e91776f04426bfa8427fb2ec1d472471345072bd292935e171dec4eb8e550e727e1135a789e7f8e6ded49a90d91ab5e9e789b58722

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
